SELECT ROUND(AVG(LENGTH), 2) AS AVERAGE_LENGTH
FROM (
    SELECT 
        CASE 
            WHEN LENGTH IS NULL OR LENGTH <= 10 THEN 10 
            ELSE LENGTH 
        END AS LENGTH
    FROM FISH_INFO
) AS adjusted_lengths;
