-- 코드를 입력하세요
SELECT A.FOOD_TYPE,	A.REST_ID	,A.REST_NAME,	A.FAVORITES
FROM REST_INFO A, (select FOOD_TYPE,max(FAVORITES) as FAV from REST_INFO group by FOOD_TYPE) B
where A.FOOD_TYPE = B.FOOD_TYPE and A.FAVORITES = FAV
order by A.FOOD_TYPE desc