-- 코드를 입력하세요
SELECT R.FOOD_TYPE,	R.REST_ID,	R.REST_NAME	,R.FAVORITES
FROM REST_INFO R, (SELECT FOOD_TYPE ,MAX(FAVORITES)AS FAV FROM REST_INFO
                GROUP BY FOOD_TYPE) B
WHERE R.FOOD_TYPE = B.FOOD_TYPE AND R.FAVORITES = B.FAV
ORDER BY FOOD_TYPE DESC